### ISSUE TITLE
Image inks in readme.md appear broken.

### ISSUE THREAD

**Issue by cdplayer** [konstantinwerner/hub_keyboard#1]
Referencing the OLED and Digikey usb parts result in "Non-Image content-type returned" from browser. Not critical for me but you might wish to update at some point. I found when trying to see if QMK supported a hub built into keyboards similar to Apple's

**Comment by stdlogicvector** [comment]
Thanks for the comment! These links were incorrectly marked as images. I fixed the markdown, they now work as they should.
